---
production: &default
  serverPort: 2525
  baseUrl: http://www.codejobs.biz
  baseApp: /js/codejobs/components
  cookieDomain: .codejobs.biz
  facebook:
    account: codejobs
    likes: 12K
    counter: '12,000'
    clientId: 324953487621707
    clientSecret: 77d85e535c01319c86f4b150bbf87f8a
  twitter:
    account: codejobs
    followers: 80K
    counter: '80,345'
    consumerKey: D9xH0f9na6cL4oTWPldZRA
    consumerSecret: tvodkw52PiJEVxS7XskLCXeH94qnGtNdHNFbNdsUTr4
    accessToken: 461804603-uAtAvzW2EPTk5pl9O4fN9UXKTJ11fVba1ObYLbTU
    accessTokenSecret: 6xRUpNVpZLtnN3HAbEV4ZZopdU4wLcJ0TUvFTO2RaeRES
    callbackUrl: http://local.codejobs.biz/twitter/callback
    requestTokenUrl: https://api.twitter.com/oauth/request_token
    accessTokenUrl: https://api.twitter.com/oauth/access_token
    authenticateUrl: https://twitter.com/oauth/authenticate
    APIUrl: https://api.twitter.com/1.1/
    APIVersion: 1.0A
    signMethod: HMAC-SHA1
  youtube:
    account: codejobs
    subscribers: 42K
    counter: '42,000'
  socialAccount: codejobs
  views:
    minify: true
    stylusPrecompile: true
  html:
    engine: handlebars
    extension: .hbs
    layout: main
    requireJs: true
    requireJsSrc: /bower_components/requirejs/require.js
    requireJsMain: /js/main
  controllers:
    default: home
    blog:
      postPerPage: 12
  languages:
    default: es
    list: [en, es, fr, pt, ge, jp, ch]
  security:
    secret: co3j0bs.biz
  database:
    mysql:
      host: 127.0.0.1
      user: root
      password:
      database: codejobs
      port: 3306
      debug: true
      socket: /var/mysql/mysql.sock
    mongodb:
      uri: mongodb://localhost:27017/
      database: codejobs
      sessionDatabase: nodesessions

stage: &stage
  <<: *default
  baseUrl: http://stage.codejobs.biz

latest: &latest
  <<: *stage
  baseUrl: http://latest.codejobs.biz

development:
  <<: *latest
  baseUrl: http://local.codejobs.biz
  views:
    minify: false
    stylusPrecompile: false
